In [2]:
import csv 
import pandas as pd
import numpy as np

In [3]:
def last(self,n):
    return self.iloc[:,-n:]

In [4]:
# with pandas
dtCdk = pd.read_csv("data/cdk_desc.csv", delimiter=' ')
dtColCdk = dtCdk.columns.values #get all CDK columns name

dtMor = pd.read_csv("data/mordred_desc.csv")
dtColMor = dtMor.columns.values #get all CDK columns name

dtPadel = pd.read_csv("data/padel_desc.csv")
dtColPad = dtPadel.columns.values #get all CDK columns name

dtRawIC50 = pd.read_csv("data/pIC50_target.csv")
dtIC50 = dtRawIC50['pIC50']

In [7]:
# Concate all dataframe (Mordred,Padel,Cdk,Target)
mixData= pd.concat([dtMor, dtPadel, dtCdk, dtIC50], axis=1)

# Deleting id from concat data
del mixData[(dtColCdk[0])]
del mixData[(dtColMor[0])]
del mixData[(dtColPad[0])]

mixData.head()

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb,pIC50
0,21.286802,17.163126,0,0,35.167281,2.593498,4.960310,35.167281,1.302492,4.245197,...,55.468790,2.054400,17.276231,7.902827,9.373404,1825.0,47.0,3.768,148.0,4.456
1,22.230715,17.943197,0,0,35.767695,2.594316,4.972945,35.767695,1.277418,4.283387,...,57.239176,2.044256,17.279705,7.904862,9.374843,2013.0,49.0,3.969,156.0,4.347
2,22.034348,17.550674,0,1,36.026220,2.593220,4.957716,36.026220,1.286651,4.277214,...,57.468198,2.052436,20.294837,7.931773,12.363064,2061.0,47.0,2.747,152.0,6.046
3,24.643996,18.574769,0,1,41.261618,2.593298,4.959970,41.261618,1.331020,4.387019,...,64.514292,2.081106,23.789104,10.969109,12.819995,2811.0,52.0,2.347,170.0,6.710
4,24.643996,18.574769,0,2,41.261618,2.593298,4.959970,41.261618,1.331020,4.387019,...,64.514292,2.081106,23.789104,7.973728,15.815376,2811.0,52.0,2.151,170.0,6.947

In [16]:
from sklearn.model_selection import train_test_split

train,test = train_test_split(mixData,test_size=0.20, random_state=45)
train.shape, test.shape

((74, 3775), (19, 3775))

In [14]:
train.to_pickle("./pickle/train_split.pkl")
test.to_pickle("./pickle/test_split.pkl")

In [15]:
train.to_csv("./data/train_split.csv")
train.to_csv("./data/test_split.csv")